server:
  port: 8085  # chạy ở cổng 8085 cho an toàn

spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ai_service?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create # để Hibernate tự tạo/cập nhật bảng
    show-sql: true # in SQL ra log (dễ debug)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

springdoc:
  api-docs:
    path: /v3/api-docs   # nơi swagger lấy JSON mô tả API
  swagger-ui:
    path: /swagger-ui.html